server:
  port: 8080

spring:
  data:
     mongodb:
       uri: mongodb+srv://root:T5SQVhMXftV62I2h@personal-cluster.up7z6.mongodb.net/voting_service_db?retryWrites=true&w=majority&appName=personal-cluster

#spring:
#  data:
#    mongodb:
#      uri: ${MONGODB_URI}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /custom-swagger-ui
